name: Run Python Script

on:
  schedule:
    - cron: '21 23 * * *'  # This runs the script every day at 11:21 PM.

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python jersey_scrape_zillow.py  # Replace with your script name
